### ISSUE TITLE
Finish front-end for Profile Page

### ISSUE THREAD

**Issue by finbud2024** [finbud2024/Finbud#64]
- [x] Finish front end profile page
- [x] replace logout button from nav bar as User's icon with dropdown menu (sam as service) cotains item: Profile, Logout
- [x] Profile page needs to be able to pull account data from backend and display correctly
- [x] profile page need to be able to have option for uploading image for user's pofile
- [x] profile page need to have the option to save changes down to database

**Comment by hphng** [comment]
- Need to resize the resolution of user image in order to fit localStorage or sessionStorage
- Find a solution to save user information (Indexed DB)
