### ISSUE TITLE
Update Chat - View

### ISSUE THREAD

**Issue by DungLe2911** [finbud2024/Finbud#75]
- [x]  Push guidance button up (in between chatframe)
- [x] Reflect user avatar + user  in chatframe when prompt question 
- [x] change tag in guidance button component from ul to ol to show numbering instead of dots
- [x] new user add question to empty chat ( new) does not crate new chat
- [x] when chat bot answer is out of frame, should always scroll to the bottom of the chat

**Comment by hphng** [comment]
Problems:
- Scroll Chat Frame down when the conversation is out of frame (@DungLe2911 will handle it)
